In [9]:
import numpy as np

In [11]:
# 브로드 캐스팅
nums = np.array([10,20,30,40])

In [17]:
nums2 = nums *2
print(nums2) # 각각 해주는게 브로드 캐스팅!

[20 40 60 80]


In [25]:
nums3 = nums - 5
print(nums3)

[ 5 15 25 35]


In [27]:
data = np.column_stack(([10,20,30],[1,2,3],[100,200,300]))
print(data)

[[ 10   1 100]
 [ 20   2 200]
 [ 30   3 300]]
